In [8]:
import tweepy
import pandas as pd

In [10]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api=tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

In [11]:
import time

hashtag="#OprahMeganHarry OR #MeganandHarryonOprah OR #meghanandharry"  


start_date ="2021-03-08"  #orario utc
end_date = "2021-03-09"

list_tweet=[]

backoff_counter = 1      
while True:
    try:
        for tweet in tweepy.Cursor(api.search,q=hashtag, since=start_date,until=end_date).items():
            try:
                    retweeted_status = tweet.retweeted_status
        
            except AttributeError:
                    retweeted_status = "None"
       
            list_tweet.append([tweet.created_at, tweet.id, tweet.id_str, tweet.text, retweeted_status, tweet.retweet_count, tweet.user.id_str,tweet.user.screen_name, tweet.user.location, tweet.lang, tweet.entities['hashtags'], tweet.entities['user_mentions'], tweet.coordinates]) 
        break
    except tweepy.TweepError as e:
        print(e.reason)
        time.sleep(60*backoff_counter)
        backoff_counter += 1
        continue

Rate limit reached. Sleeping for: 751
Rate limit reached. Sleeping for: 811
Rate limit reached. Sleeping for: 812
Rate limit reached. Sleeping for: 813
Rate limit reached. Sleeping for: 812
Rate limit reached. Sleeping for: 803
Rate limit reached. Sleeping for: 791
Rate limit reached. Sleeping for: 740
Rate limit reached. Sleeping for: 810
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 810
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 806
Rate limit reached. Sleeping for: 810
Rate limit reached. Sleeping for: 811
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 810
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 808
Rate limit reached. Sleeping for: 808
Rate limit reached. Sleeping for: 807
Rate limit reached. Sleeping for: 810
Rate limit reached. Sleeping for: 808
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 810
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 809
Rate limit reached. Sleeping for: 811
Rate limit reached. Sleeping for: 812
Rate limit reached. Sleeping for: 812
Rate limit reached. Sleeping for: 811
Rate limit reached. Sleeping for: 814
Rate limit reached. Sleeping for: 815

In [12]:
tweets = pd.DataFrame(list_tweet[1:],columns=['created_at','id','id_str','text','retweeted_status','retweet_count','user.id_str','user.screen_name','user.location','lang','entities.hashtags','entities.user_mentions', 'coordinates'])

In [13]:
tweets

,created_at,id,id_str,text,retweeted_status,retweet_count,user.id_str,user.screen_name,user.location,lang,entities.hashtags,entities.user_mentions,coordinates
0,2021-03-08 23:59:54,1369075433208225792,1369075433208225792,#HarryandMeghanonOprah #MeghanAndHarry #OprahM...,None,0,308823735,FML_USA,"Austin, TX",und,"[{'text': 'HarryandMeghanonOprah', 'indices': ...",[],None
1,2021-03-08 23:59:53,1369075432314789891,1369075432314789891,Right I'm watching #MeghanAndHarry I'm on no-o...,None,0,2298249935,NasceraMahria,"Airdrie, Scotland",en,"[{'text': 'MeghanAndHarry', 'indices': [19, 34]}]",[],None
2,2021-03-08 23:59:51,1369075422886047744,1369075422886047744,RT @Iromg: What an absolute shower of shite th...,Status(_api=<tweepy.api.API object at 0x000002...,445,333389010,gettingoninyrs,Bridport Dorset,en,[],"[{'screen_name': 'Iromg', 'name': 'Mike Graham...",None
3,2021-03-08 23:59:51,1369075421204131842,1369075421204131842,RT @bashperkinsx: Harry had to witness his mot...,Status(_api=<tweepy.api.API object at 0x000002...,858,1107243349,fiandkaya,Wexford & London,en,[],"[{'screen_name': 'bashperkinsx', 'name': 'sash...",None
4,2021-03-08 23:59:47,1369075405722894337,1369075405722894337,So heartbreaking watching #MeghanAndHarry. I c...,None,0,148756213,BeckyFell,,en,"[{'text': 'MeghanAndHarry', 'indices': [26, 41]}]",[],None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95223,2021-03-08 00:00:40,1368713239966670848,1368713239966670848,RT @VeeFraz: Protect Meghan Markle at all cost...,Status(_api=<tweepy.api.API object at 0x000002...,56,2589736605,prwettistacy,United Kingdom,en,[],"[{'screen_name': 'VeeFraz', 'name': 'Vash', 'i...",None
95224,2021-03-08 00:00:29,1368713193871278082,1368713193871278082,RT @jameelajamil: You only ever work this hard...,Status(_api=<tweepy.api.API object at 0x000002...,252,501234691,ATrulyFan,España,en,"[{'text': 'MeghanAndHarry', 'indices': [86, 10...","[{'screen_name': 'jameelajamil', 'name': 'Jame...",None
95225,2021-03-08 00:00:27,1368713186057347079,1368713186057347079,BFD. The royal family and the press owe them a...,None,1,35445051,IamAlexRafael,"Queens, NY",en,"[{'text': 'MeghanMarkle', 'indices': [58, 71]}...",[],None
95226,2021-03-08 00:00:18,1368713146496598018,1368713146496598018,One hour to go until the #MeghanAndHarry inter...,None,1,991975703838183430,TrueRoyaltyTV,,en,"[{'text': 'MeghanAndHarry', 'indices': [25, 40...",[],None
95227,2021-03-08 00:00:16,1368713137298497544,1368713137298497544,RT @UnRoyalReporter: Here’s the first episode ...,Status(_api=<tweepy.api.API object at 0x000002...,7,1233467099953143808,sirnutsandbull1,,en,"[{'text': 'MeghanMarkle', 'indices': [52, 65]}...","[{'screen_name': 'UnRoyalReporter', 'name': 'R...",None

In [14]:
tweets.to_csv('MH_completo')