In [ ]:
#visualizzazioni dati covid e parenti

In [1]:
#import dati
import pandas as pd
import numpy as np
covid=pd.read_excel("C:/Users/aless/OneDrive/Desktop/AleBicocca/Data Science/Anno 2/Lab Biosciences/Project/Dati_Covid/covid_statistics.xlsx")
parenti=pd.read_excel("C:/Users/aless/OneDrive/Desktop/AleBicocca/Data Science/Anno 2/Lab Biosciences/Project/Dati_Covid/parenti_statistics.xlsx")

In [2]:
covid=covid.drop("Unnamed: 0",axis=1)
parenti=parenti.drop("Unnamed: 0",axis=1)

In [3]:
covid

,Country,Principal_Author,Funding_country,Sum,FTE_researchers,st_value,pct_prin_auth,pct_fun_cou,pct_sum,Country_code,pct_fun_cou_eti,pct_prin_auth_eti,pct_sum_eti
0,United States,20406,20779,41185,1632644.54,25.226,29.13,29.67,29.40,USA,29.67%,29.13%,29.4%
1,China,9983,10089,20072,2299311.18,8.730,14.25,14.40,14.33,CHN,14.4%,14.25%,14.33%
2,Italy,6420,6385,12805,170260.70,75.208,9.17,9.12,9.14,ITA,9.12%,9.17%,9.14%
3,United Kingdom,5526,5386,10912,333345.60,32.735,7.89,7.69,7.79,UK,7.69%,7.89%,7.79%
4,Spain,2543,2539,5082,152612.33,33.300,3.63,3.62,3.63,SPA,3.62%,3.63%,3.63%
5,France,2312,2315,4627,326664.92,14.164,3.30,3.31,3.30,FRA,3.31%,3.3%,3.3%
6,Germany,2111,2133,4244,467442.56,9.079,3.01,3.05,3.03,GER,3.05%,3.01%,3.03%
7,Canada,1735,1759,3494,166834.50,20.943,2.48,2.51,2.49,CAN,2.51%,2.48%,2.49%
8,Japan,960,999,1959,688639.21,2.845,1.37,1.43,1.40,JAP,1.43%,1.37%,1.4%
9,Singapore,738,744,1482,42414.18,34.941,1.05,1.06,1.06,SGP,1.06%,1.05%,1.06%
10,Netherlands,678,683,1361,109996.56,12.373,0.97,0.98,0.97,NED,0.98%,0.97%,0.97%
11,Others,0,0,0,0.00,0.000,24.50,24.50,24.50,Others,24.5%,24.5%,24.5%

In [12]:
stand=[]
for index,row in covid[0:11].iterrows():
    val=round(row['Principal_Author']*1000/row['FTE_researchers'],3) #moltiplico per 100 per avere migliore risultato alla fine
    stand.append(val)
covid=covid[0:11]
covid['st_value_new']=stand
covid
#ordinamento per valore assoluto

<ipython-input-12-da18155cd3d1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  covid['st_value_new']=stand

,Country,Principal_Author,Funding_country,Sum,FTE_researchers,st_value,pct_prin_auth,pct_fun_cou,pct_sum,Country_code,pct_fun_cou_eti,pct_prin_auth_eti,pct_sum_eti,st_value_new
0,United States,20406,20779,41185,1632644.54,25.226,29.13,29.67,29.40,USA,29.67%,29.13%,29.4%,12.499
1,China,9983,10089,20072,2299311.18,8.730,14.25,14.40,14.33,CHN,14.4%,14.25%,14.33%,4.342
2,Italy,6420,6385,12805,170260.70,75.208,9.17,9.12,9.14,ITA,9.12%,9.17%,9.14%,37.707
3,United Kingdom,5526,5386,10912,333345.60,32.735,7.89,7.69,7.79,UK,7.69%,7.89%,7.79%,16.577
4,Spain,2543,2539,5082,152612.33,33.300,3.63,3.62,3.63,SPA,3.62%,3.63%,3.63%,16.663
5,France,2312,2315,4627,326664.92,14.164,3.30,3.31,3.30,FRA,3.31%,3.3%,3.3%,7.078
6,Germany,2111,2133,4244,467442.56,9.079,3.01,3.05,3.03,GER,3.05%,3.01%,3.03%,4.516
7,Canada,1735,1759,3494,166834.50,20.943,2.48,2.51,2.49,CAN,2.51%,2.48%,2.49%,10.400
8,Japan,960,999,1959,688639.21,2.845,1.37,1.43,1.40,JAP,1.43%,1.37%,1.4%,1.394
9,Singapore,738,744,1482,42414.18,34.941,1.05,1.06,1.06,SGP,1.06%,1.05%,1.06%,17.400
10,Netherlands,678,683,1361,109996.56,12.373,0.97,0.98,0.97,NED,0.98%,0.97%,0.97%,6.164

In [4]:
parenti

,Country,Principal_Author,Funding_country,Sum,FTE_researchers_mean,st_value,pct_prin_auth,pct_fun_cou,pct_sum,Country_code,pct_fun_cou_eti,pct_prin_auth_eti,pct_sum_eti
0,United States,3974,4248,8222,1220328.65,6.738,33.35,35.65,34.50,USA,35.65%,33.35%,34.5%
1,China,2903,3069,5972,1325785.88,4.504,24.36,25.76,25.06,CHN,25.76%,24.36%,25.06%
2,Japan,584,584,1168,662905.70,1.762,4.90,4.90,4.90,JAP,4.9%,4.9%,4.9%
3,Canada,528,530,1058,145524.56,7.270,4.43,4.45,4.44,CAN,4.45%,4.43%,4.44%
4,United Kingdom,489,512,1001,253041.09,3.956,4.10,4.30,4.20,UK,4.3%,4.1%,4.2%
5,Germany,474,482,956,330292.10,2.894,3.98,4.04,4.01,GER,4.04%,3.98%,4.01%
6,Netherlands,457,452,909,64254.75,14.147,3.84,3.79,3.81,NED,3.79%,3.84%,3.81%
7,France,320,322,642,239758.57,2.678,2.69,2.70,2.69,FRA,2.7%,2.69%,2.69%
8,Spain,223,225,448,117501.04,3.813,1.87,1.89,1.88,SPA,1.89%,1.87%,1.88%
9,Italy,216,223,439,103782.26,4.230,1.81,1.87,1.84,ITA,1.87%,1.81%,1.84%
10,Singapore,217,213,430,29287.38,14.682,1.82,1.79,1.80,SGP,1.79%,1.82%,1.8%
11,Others,0,0,0,0.00,0.000,10.90,10.90,10.90,Others,10.9%,10.9%,10.9%

In [14]:
stand=[]
for index,row in parenti[0:11].iterrows():
    val=round(row['Principal_Author']*1000/row['FTE_researchers_mean'],3) #moltiplico per 100 per avere migliore risultato alla fine
    stand.append(val)
parenti=parenti[0:11]
parenti['st_value_new']=stand
parenti
#ordinamento per valore assoluto

<ipython-input-14-005657c85682>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  parenti['st_value_new']=stand

,Country,Principal_Author,Funding_country,Sum,FTE_researchers_mean,st_value,pct_prin_auth,pct_fun_cou,pct_sum,Country_code,pct_fun_cou_eti,pct_prin_auth_eti,pct_sum_eti,st_value_new
0,United States,3974,4248,8222,1220328.65,6.738,33.35,35.65,34.50,USA,35.65%,33.35%,34.5%,3.256
1,China,2903,3069,5972,1325785.88,4.504,24.36,25.76,25.06,CHN,25.76%,24.36%,25.06%,2.190
2,Japan,584,584,1168,662905.70,1.762,4.90,4.90,4.90,JAP,4.9%,4.9%,4.9%,0.881
3,Canada,528,530,1058,145524.56,7.270,4.43,4.45,4.44,CAN,4.45%,4.43%,4.44%,3.628
4,United Kingdom,489,512,1001,253041.09,3.956,4.10,4.30,4.20,UK,4.3%,4.1%,4.2%,1.932
5,Germany,474,482,956,330292.10,2.894,3.98,4.04,4.01,GER,4.04%,3.98%,4.01%,1.435
6,Netherlands,457,452,909,64254.75,14.147,3.84,3.79,3.81,NED,3.79%,3.84%,3.81%,7.112
7,France,320,322,642,239758.57,2.678,2.69,2.70,2.69,FRA,2.7%,2.69%,2.69%,1.335
8,Spain,223,225,448,117501.04,3.813,1.87,1.89,1.88,SPA,1.89%,1.87%,1.88%,1.898
9,Italy,216,223,439,103782.26,4.230,1.81,1.87,1.84,ITA,1.87%,1.81%,1.84%,2.081
10,Singapore,217,213,430,29287.38,14.682,1.82,1.79,1.80,SGP,1.79%,1.82%,1.8%,7.409

In [ ]:
#chi è migliorato/peggiorato di più? chi ha confermato vantaggio?

In [19]:
merge=pd.merge(covid[['Country','Country_code','Sum','Principal_Author','pct_sum','st_value','st_value_new']],parenti[['Country','Sum','Principal_Author','pct_sum','st_value','st_value_new']], on='Country')
merge.rename(columns={'Sum_x': 'Total_projects_covid', 'Sum_y': 'Total_projects_coronavirus','pct_sum_x':'pct_sum_cov','pct_sum_y':'pct_sum_corona','st_value_x':'st_value_cov','st_value_y':'st_value_coronavirus','st_value_new_x':'st_value_new_cov','st_value_new_y':'st_value_new_coronavirus','Principal_Author_x':'Principal_Author_cov','Principal_Author_y':'Principal_Author_coronavirus'}, inplace=True)
merge

,Country,Country_code,Total_projects_covid,Principal_Author_cov,pct_sum_cov,st_value_cov,st_value_new_cov,Total_projects_coronavirus,Principal_Author_coronavirus,pct_sum_corona,st_value_coronavirus,st_value_new_coronavirus
0,United States,USA,41185,20406,29.40,25.226,12.499,8222,3974,34.50,6.738,3.256
1,China,CHN,20072,9983,14.33,8.730,4.342,5972,2903,25.06,4.504,2.190
2,Italy,ITA,12805,6420,9.14,75.208,37.707,439,216,1.84,4.230,2.081
3,United Kingdom,UK,10912,5526,7.79,32.735,16.577,1001,489,4.20,3.956,1.932
4,Spain,SPA,5082,2543,3.63,33.300,16.663,448,223,1.88,3.813,1.898
5,France,FRA,4627,2312,3.30,14.164,7.078,642,320,2.69,2.678,1.335
6,Germany,GER,4244,2111,3.03,9.079,4.516,956,474,4.01,2.894,1.435
7,Canada,CAN,3494,1735,2.49,20.943,10.400,1058,528,4.44,7.270,3.628
8,Japan,JAP,1959,960,1.40,2.845,1.394,1168,584,4.90,1.762,0.881
9,Singapore,SGP,1482,738,1.06,34.941,17.400,430,217,1.80,14.682,7.409
10,Netherlands,NED,1361,678,0.97,12.373,6.164,909,457,3.81,14.147,7.112

In [20]:
#chi è migliorato di più tra i paesi? calcoliamo un indicatore c he sfrutta i valori standardizzati
delta_pct=[]
delta_pct_eti=[]
indice_std=[]
indice=[]
indice_pa_std=[]
merge=merge[0:11]
for index,row in merge.iterrows():
    
    delta=round((row['pct_sum_cov'] - row['pct_sum_corona']),2)
    delta_pct.append(delta)
    
    delta_pct_eti.append(str(delta)+"%")
    ind=round((row['Total_projects_covid'] - row['Total_projects_coronavirus'])/row['Total_projects_covid'],2)
    indice.append(ind)
    
    ind_std=round((row['st_value_cov'] - row['st_value_coronavirus'])/row['st_value_cov'],2)
    indice_std.append(ind_std)
    
    ind_pa=round((row['st_value_new_cov'] - row['st_value_new_coronavirus'])/row['st_value_new_cov'],2)
    indice_pa_std.append(ind_pa)
    
merge['delta_pct']=delta_pct
merge['delta_pct_eti']=delta_pct_eti
merge['indice_std']=indice_std
merge['indice']=indice 
merge['indice_pa_std']=indice_pa_std
merge

<ipython-input-20-510aa519131e>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['delta_pct']=delta_pct
<ipython-input-20-510aa519131e>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['delta_pct_eti']=delta_pct_eti
<ipython-input-20-510aa519131e>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['indice_std']=indice_std
<ipython-input-20-510aa519131e>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['indice']=indice
<ipython-input-20-510aa519131e>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merge['indice_pa_std']=indice_pa_std

,Country,Country_code,Total_projects_covid,Principal_Author_cov,pct_sum_cov,st_value_cov,st_value_new_cov,Total_projects_coronavirus,Principal_Author_coronavirus,pct_sum_corona,st_value_coronavirus,st_value_new_coronavirus,delta_pct,delta_pct_eti,indice_std,indice,indice_pa_std
0,United States,USA,41185,20406,29.40,25.226,12.499,8222,3974,34.50,6.738,3.256,-5.10,-5.1%,0.73,0.80,0.74
1,China,CHN,20072,9983,14.33,8.730,4.342,5972,2903,25.06,4.504,2.190,-10.73,-10.73%,0.48,0.70,0.50
2,Italy,ITA,12805,6420,9.14,75.208,37.707,439,216,1.84,4.230,2.081,7.30,7.3%,0.94,0.97,0.94
3,United Kingdom,UK,10912,5526,7.79,32.735,16.577,1001,489,4.20,3.956,1.932,3.59,3.59%,0.88,0.91,0.88
4,Spain,SPA,5082,2543,3.63,33.300,16.663,448,223,1.88,3.813,1.898,1.75,1.75%,0.89,0.91,0.89
5,France,FRA,4627,2312,3.30,14.164,7.078,642,320,2.69,2.678,1.335,0.61,0.61%,0.81,0.86,0.81
6,Germany,GER,4244,2111,3.03,9.079,4.516,956,474,4.01,2.894,1.435,-0.98,-0.98%,0.68,0.77,0.68
7,Canada,CAN,3494,1735,2.49,20.943,10.400,1058,528,4.44,7.270,3.628,-1.95,-1.95%,0.65,0.70,0.65
8,Japan,JAP,1959,960,1.40,2.845,1.394,1168,584,4.90,1.762,0.881,-3.50,-3.5%,0.38,0.40,0.37
9,Singapore,SGP,1482,738,1.06,34.941,17.400,430,217,1.80,14.682,7.409,-0.74,-0.74%,0.58,0.71,0.57
10,Netherlands,NED,1361,678,0.97,12.373,6.164,909,457,3.81,14.147,7.112,-2.84,-2.84%,-0.14,0.33,-0.15

In [21]:
merge.to_excel('indicatori_new.xlsx')